version: '3.8'

services:
  server:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    hostname: go-server
    networks:
      - gonetwork
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/app

  database:
    image: postgres:latest
    container_name: postgres
    hostname: postgres-db
    networks: 
      - gonetwork
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  gonetwork:
    driver: bridge
